# Generated by Django 4.2.2 on 2023-07-04 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Access', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile_data',
            name='gender',
            field=models.BooleanField(null=True),
        ),
    ]
