# Generated by Django 4.2.2 on 2023-07-04 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Access', '0002_alter_profile_data_gender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile_data',
            old_name='gender',
            new_name='Female',
        ),
        migrations.AddField(
            model_name='profile_data',
            name='Male',
            field=models.BooleanField(null=True),
        ),
    ]
