# Generated by Django 4.2.2 on 2023-07-04 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Access', '0003_rename_gender_profile_data_female_profile_data_male'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile_data',
            name='Female',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='profile_data',
            name='Male',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
