# Generated by Django 4.2.2 on 2023-07-04 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Access', '0004_alter_profile_data_female_alter_profile_data_male'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile_data',
            old_name='Female',
            new_name='female',
        ),
        migrations.RenameField(
            model_name='profile_data',
            old_name='Male',
            new_name='male',
        ),
    ]
