# Generated by Django 4.2.2 on 2023-07-04 13:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Access', '0005_rename_female_profile_data_female_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile_data',
            name='user',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
