# Generated by Django 4.2.2 on 2023-07-06 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Access', '0006_alter_profile_data_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile_data',
            name='female',
        ),
        migrations.RemoveField(
            model_name='profile_data',
            name='male',
        ),
        migrations.AddField(
            model_name='profile_data',
            name='gender',
            field=models.BooleanField(null=True),
        ),
    ]
