# Generated by Django 4.2.2 on 2023-07-04 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0005_profile_data'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile_Data',
        ),
    ]
