# Generated by Django 4.2.2 on 2023-07-21 06:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Posts', '0007_remove_post_love'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='love',
            field=models.ManyToManyField(related_name='lovesTable', to=settings.AUTH_USER_MODEL),
        ),
    ]
